### PR TITLE
bump to cmark-gfm 0.28.3.gfm.16

### PR DESCRIPTION
**Pull request by kivikakk**
Includes a fix which causes footnote references being rendered inside table cells.

/cc @gjtorikian @digitalmoksha

### CODE REVIEW

**Comment by kivikakk** [comment]
0.17.13 has been released with this fix. /cc @digitalmoksha

**Comment by gjtorikian** [comment]
Oh, does `script/update_modules` not import changes?

**Comment by kivikakk** [comment]
It runs `make`, which does indeed update the C sources, so, yeah, it does!

**Comment by gjtorikian** [comment]
I think I got confused because of the changes not in the submodule folder. 🙈 Ignore me!

**Comment by digitalmoksha** [comment]
@kivikakk Thank you!  Works like charm...

**Pull request merged**
