### PR TITLE
Readme defintion of `each` seems ot conflict with implementation

### PR DESCRIPTION
**Pull request by stellarpower**
The readme mentions that Node#each will iterate on a node and its first-level children (implying self will be yielded), but from [the source file](https://github.com/gjtorikian/commonmarker/blob/55c3b03708b31f1af37a53b3312f91400594223d/lib/commonmarker/node.rb#L27) it seems that only the children are yielded.

Some basic testing seems to yield just the children for me, but feel free to correct me if I'm missing something here :)

### CODE REVIEW

**Comment by gjtorikian** [comment]
Yes, you are correct. Thank you for the correction!

**Comment by stellarpower** [comment]
Very welcome! A map might be useful too - but I guess that may have been left out intentionally to avoid ambiguity with walk.

**Comment by gjtorikian** [comment]
I think the only for sure complete list is here: https://github.com/gjtorikian/commonmarker/blob/58d4c910112df2aab84e193841051b616ea08e6e/ext/commonmarker/src/node.rs#L40

It’s possible that the underlying comrak lib has more nodes that I haven’t yet ported over: https://github.com/kivikakk/comrak/blob/c36419327a09bfbe1326baf34db23f2c3f744f6f/src/nodes.rs#L15

**Comment by stellarpower** [comment]
Thanks, the rust docs were what I'd been referring to. Somehow ruby is able to tab-complete some sensible options for the symbol, and as much as I like symbols, the disadvantage compared to a strictly-typed enum is it's hard to know all the options or what the right wording is. Yes python, I'm looking at you, with all those string keyword arguments rammed into one functions's signature that completely change the behaviour.

Maybe something to add (and that could be)? I was looking at the enum values, and given it's rust, I originally assumed that the enumeration was consumed on the ruby side and the symbol was converted to it via some generated boilerplate string matching. But I guess from this you're calling to_s and rust is then handling it. So that's not so trivial to manage then.

**Pull request merged**
