### PR TITLE
Bump dependencies to support tasklists

### PR DESCRIPTION
**Pull request by gjtorikian**
Re: https://github.com/gjtorikian/commonmarker/issues/64#issuecomment-461464897

Something is a bit missing when it comes to walking the nodes around a task list...it ends up in a recursion. Not sure if this is a problem here or upstream just yet.

### CODE REVIEW

**Comment by kivikakk** [comment]
> `oh good lord`

**Comment by gjtorikian** [comment]
> [I continue to hate computers](https://github.com/gjtorikian/commonmarker/commit/2d4074c4fe70df0a260cbb500708266fa1fafd2b#diff-b7bbe63048824ccac1b8f32e2f5744d5)

**Comment by kivikakk** [comment]
image

**Comment by gjtorikian** [comment]
@kivikakk I believe something upstream is not quite right, but I haven't identified what it is just yet. 

In this gem, parsing a file was

``` ruby
doc = CommonMarker.render_doc(text, :DEFAULT, %i[tasklist])
doc.to_html
``` 

works precisely as expected. `to_html` relies on the C lib's `cmark_render_html` function.

But when attempting to step through and render individual nodes:

``` ruby
CommonMarker::HtmlRenderer.new.render(doc)
```

the generation hangs. 

That renderer depends on a node's type string to understand what to do. According to just `puts node.type_string.to_s`, this emits `list`, not an expected `tasklist`. Would you be able to help me sleuth this, or, if you're pressed for time, point out to me where I can go to look a bit further?

**Comment by kivikakk** [comment]
Ugh, I cannot believe what has happened here:

* commonmarker uses `cmark_node_set_user_data` and `cmark_node_get_user_data` to store a cache of the Ruby `Node` against the cmark node.
* the tasklist extension uses the same functions to store `CMARK_TASKLIST_CHECKED` and `CMARK_TASKLIST_NOCHECKED`, which are an enum.
* this means when storing `CMARK_TASKLIST_NOCHECKED`, the cached node is forgotten. (memory leak!)
* when storing `CMARK_TASKLIST_CHECKED`, we return it immediately as a `VALUE` in `rb_node_to_value`. The `VALUE` 1 is the Fixnum `0`.
* in `CommonMarker::Node#each`, we get the first child and then repeatedly call `next` on it.
* `Fixnum#next` returns the next integer, i.e. it sits there looping through all integers starting at zero.

I don't have time to work on a fix for this atm, but hopefully this is enough of a pointer.

**Comment by kivikakk** [comment]
Relevant sections of code:

https://github.com/gjtorikian/commonmarker/blob/b9e57516f8e1ed66abc64f5f5e1447623c82b4cb/ext/commonmarker/commonmarker.c#L83-L101

https://github.com/gjtorikian/commonmarker/blob/b9e57516f8e1ed66abc64f5f5e1447623c82b4cb/lib/commonmarker/node.rb#L55-L65

**Comment by kivikakk** [comment]
And:

https://github.com/gjtorikian/commonmarker/blob/4da613e916de4895cb35bbdfc696ed9bf1f3f341/ext/commonmarker/tasklist.c#L7-L10

https://github.com/gjtorikian/commonmarker/blob/4da613e916de4895cb35bbdfc696ed9bf1f3f341/ext/commonmarker/tasklist.c#L65-L71

**Comment by kivikakk** [comment]
If possible, the tasklist code in `cmark-gfm` should use the node opaque area like the table extension does. (I haven't looked into this yet and didn't write the tasklist extension, so not sure if that's something that'll work or not.)

**Comment by gjtorikian** [comment]
> but hopefully this is enough of a pointer

I C what you did there hyuck hyuck

Thanks a bunch! This helps a ton.

**Comment by kivikakk** [comment]
> > but hopefully this is enough of a pointer
> 
> I C what you did there hyuck hyuck

I can't even admit to doing that on purpose /o\

**Comment by kivikakk** [comment]
:tada:

**Comment by oliverguenther** [comment]
Great stuff, thanks for working on this! :bowing_man:

**Pull request merged**
