### PR TITLE
No cmake required!

### PR DESCRIPTION
**Pull request by kivikakk**
WHATAMESS

We import the source tree, à la [cmark-gfm-hs](https://github.com/kivikakk/cmark-gfm-hs), with a Makefile to assist maintainers to pull the changes in. We don't need a LOT of extra `extconf.rb` messing around, since it just all compiles together clean.

~~There's one line (left commented) in `extconf.rb` I'm unsure about whether it'd be required on Windows; will wait on AppVeyor to complain or not.~~ _gone_

/cc @gjtorikian

### CODE REVIEW

**Comment by gjtorikian** [comment]
🙀 

How come the individual C files need to be brought in here into _ext/commonmarker/_? Can't the Makefile build `cmark`'s _src_ dir ?

**Comment by kivikakk** [comment]
NOPE. Tried that, and mkmf was like "lol, I see your sources, and will acknowledge that their objects should be part of the resulting build … but I won't build them 😉 "

(╯°□°）╯︵ ┻━┻

**Comment by kivikakk** [comment]
(it only looks in `srcdir`, and there can only be one `srcdir`)

**Comment by kivikakk** [comment]
(so even if you specify all the sources in `$srcs`, if they're not found in `srcdir`, the resulting `Makefile` just won't see them and build them, but their objects will still be listed in `OBJS` and you'll get this:

screen shot 2017-12-06 at 8 23 16 am

(/ .□.)\ ︵╰(゜Д゜)╯︵ /(.□. \))

**Pull request merged**
