### PR TITLE
Allow namespaces in tag names.

### PR DESCRIPTION
**Pull request by ioquatix**
Is there any documentation about how to run `re2c` to minimise the `scanners.c` diff?

### CODE REVIEW

**Comment by kivikakk** [comment]
These come from the upstream [cmark](https://github.com/CommonMark/cmark) project, which we track. Its `Makefile` includes a rule for regenerating `scanners.c`.

This change should technically be directed to that project, as we copy changes from it via [cmark-gfm](https://github.com/github/cmark-gfm), but I don't believe any current Commonmarker maintainer has write access to cmark-gfm at present, so there's no guarantee any upstream cmark changes will make it through in a timely fashion. A change to `scanners.re` and `scanners.c` in Commonmarker would be lost next time we sync with cmark-gfm.

This should perhaps first be proposed as an update to [the spec itself](https://github.com/CommonMark/commonmark), which [defines HTML tags](https://spec.commonmark.org/0.29/#raw-html) and is responsible for the `tagname` definition there.

@gjtorikian What do you think of the current situation? As it stands I'm not sure cmark-gfm is maintained, which would mean we lose the ability to track upstream cmark changes.

**Comment by ioquatix** [comment]
I'm happy to make a proposal to change the spec but I have no idea where to begin, and maybe it's rude but I just want this one feature to work, it's a blocker for me. I can just make a fork, but that doesn't seem like nice behaviour TBH.

**Comment by movermeyer** [comment]
I would like to voice opposition to anything that makes this gem deviate from the Commonmark spec in any way. We're relying on this gem to be a faithful implementation of the spec, with a nice Ruby interface.

It should accept no more, and no less than what the spec says.

**Comment by ioquatix** [comment]
Sure, that makes sense, so we should update the spec then?

**Comment by kivikakk** [comment]
@ioquatix Yes — it is thankfully not too hard. Fork the [`commonmark/commonmark-spec`](https://github.com/commonmark/commonmark-spec) repo, and open a PR [making the necessary changes to `spec.txt`](https://github.com/commonmark/commonmark-spec/blob/84a8994886d406eabb9780c207551561fd8816b8/spec.txt#L8908) — I've linked the Raw HTML section of it here. You'll want to update the paragraph that begins: `A [tag name](@) consists of …`.

A bit further down, examples of valid and invalid HTML tags follow. Add some examples showing how namespaces _should_ work, i.e. that a tag like `<a:b>` should be passed through unchanged, not translated to `&lt;a:b&gt;`. Once accepted and included in a new version, compliant implementations will be out of spec until the new examples pass.

**Comment by ioquatix** [comment]
@kivikakk thanks for your help.

**Comment by kivikakk** [comment]
@ioquatix You're welcome! Feel free to @mention me in the new PR and I'll do what I can to help shepherd it along.

**Comment by gjtorikian** [comment]
> What do you think of the current situation? As it stands I'm not sure cmark-gfm is maintained, which would mean we lose the ability to track upstream cmark changes.

It's a bad situation, to be sure. I doubt that `cmark-gfm` will be modified in the future; it does what it needs to for GitHub. I keep thinking about moving the backend for this gem to Rust (https://github.com/gjtorikian/commonmarker/issues/107), both for added safety and for more incremental improvements, but I haven't had a chance to look at those implications yet.

Regardless, for this specific change, I'm afraid it will have to adhere first to the Commonmark spec (which takes precedence over GitHub's extensions spec). There's already a discussion for it on https://github.com/commonmark/commonmark-spec/pull/648 which suggests it's not a simple change unfortunately. When/if it gets in there I'd be open to including it here (with tests). Hopefully it's a small enough change whereby if GitHub does update their C code for something else we can apply the regex diff here. (Or maybe by then we'll stop using their repo.)

> We're relying on this gem to be a faithful implementation of the spec, with a nice Ruby interface.

PS If Shopify is using this gem, please consider sponsoring it.

**Comment by ioquatix** [comment]
Just in case anyone stumbles across this issue, I made a fork of `commonmarker` and reworked a bunch of the C code to be more parser centric.

https://github.com/ioquatix/markly/

It supports tags with XML namespaces and almost passes the cmark spec, except for one failure which is questionable on the part of the spec. I also found that HTML5 definition of how to parse a tag name is at odds with cmark, so I suspect change will eventually happen.

**Review by crimscim — COMMENTED** [review]
Hei

**Pull request closed without merging**
