### PR TITLE
Test the new integrated rb-sys

### PR DESCRIPTION
**Pull request by gjtorikian**
xref https://github.com/oxidize-rb/rb-sys/pull/144

### CODE REVIEW

**Comment by ianks** [comment]
0.9.63 has been released which officially releases this!

**Comment by gjtorikian** [comment]
> 0.9.63 has been released which officially releases this!

Heck yeah, thank you!

**Comment by ianks** [comment]
I need to add a better error message, but now the extension task expects the crate name: `RbSys::ExtensionTask.new(CRATE_NAME_FROM_CARGO_TOML_HERE)`

**Comment by ianks** [comment]
This diff should fix it:

```diff
diff --git i/commonmarker.gemspec w/commonmarker.gemspec
index a45619e..51b564b 100644
--- i/commonmarker.gemspec
+++ w/commonmarker.gemspec
@@ -17,7 +17,7 @@ Gem::Specification.new do |spec|
   # https://github.com/rubygems/rubygems/pull/5852#issuecomment-1231118509
   spec.required_rubygems_version = ">= 3.3.22"
 
-  spec.files = ["LICENSE.txt", "README.md", "Cargo.lock"]
+  spec.files = ["LICENSE.txt", "README.md", "Cargo.lock", "Cargo.toml"]
   spec.files += Dir.glob("lib/**/*.rb")
   spec.files += Dir.glob("ext/**/*.{rs,toml,lock,rb}")
   spec.bindir = "exe"
```

**Comment by gjtorikian** [comment]
> This diff should fix it:

thanks!

**Comment by ianks** [comment]
BIG 🟥 diff, love it!

**Pull request merged**
