### PR TITLE
Support the TABLE_PREFER_STYLE_ATTRIBUTES render option

### PR DESCRIPTION
**Pull request by gfx**
https://github.com/github/cmark/pull/86
https://github.com/github/cmark/pull/87

### CODE REVIEW

**Comment by gjtorikian** [comment]
If you can throw in a Ruby test you're golden! A simple string match showing that the attribute name changes should suffice. Thanks!

**Comment by gfx** [comment]
Sure! Added tests in 5d8d953.

**Comment by kivikakk** [comment]
Excellent! Thank you.

**Comment by kivikakk** [comment]
This is now released in 0.17.8.

**Comment by gfx** [comment]
Thanks! 👏

**Pull request merged**
